name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::jupyter=1.0.0
  - conda-forge::seaborn=0.11.1
  - conda-forge::pandas=1.2.3
  - conda-forge::pip=20.3.3
  - conda-forge::pandas-profiling=3.1.0
  - conda-forge::protobuf=3.16.0
  - conda-forge::pyarrow=2.0
  - pip:
      - wandb==0.10.31