name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::mlflow=1.14.1
  - conda-forge::pyyaml=5.3.1
  - conda-forge::pip=20.3.3
  - pip:
      - hydra-core==1.0.6
      - wandb==0.10.31