name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::mlflow=1.14.1
  - conda-forge::ipython=7.21.0
  - conda-forge::notebook=6.2.0
  - conda-forge::jupyterlab=3.0.10
  - conda-forge::cookiecutter=1.7.2
  - conda-forge::hydra-core=1.0.6
  - conda-forge::matplotlib=3.3.4
  - conda-forge::pandas=1.2.3
  - conda-forge::protobuf=3.16.0
  - conda-forge::git=2.30.2
  - conda-forge::pip=20.3.3
  - pip:
      - wandb==0.10.31
