name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::pandas=1.1.4
  - conda-forge::pip=20.3.3
  - conda-forge::mlflow=1.14.1
  - conda-forge::scikit-learn=0.24.1
  - conda-forge::protobuf=3.16.0
  - pip:
      - wandb==0.10.31
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
